### ISSUE TITLE
Saving an MZmine3 project

### ISSUE THREAD

**Issue by BeniddirLab** [mzmine/mzmine3#1438]
### Basic information

* My operating system and version: Windows 11 pro
* My MZmine version: 3.4.27

### What happened

* After processing my LC-MS/MS data using the usual Feature-Based MN workflow, I was unable to save my MZmine project into a *.mzmine file. I have opened MZmine as an administrator.
* I used File  Save project as
* The screenshot has been uploaded
![error-github](https://github.com/mzmine/mzmine3/assets/134812110/3cb79109-c848-4daf-b6b9-20bbf2d23dad)

Thank you for your help.

**Comment by tomas-pluskal** [comment]
Thanks Mehdi!
I could reproduce the issue with MZmine 3.7.2.
This is the stack trace:
```
2023-07-31 11:04:32 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.IllegalArgumentException: Cannot find selected scans. while processing task Saving feature list Aligned feature list filtered gap-filled
java.lang.IllegalArgumentException: Cannot find selected scans.
	at io.github.mzmine.datamodel.features.types.FeatureDataType.saveToXML(FeatureDataType.java:104)
	at io.github.mzmine.modules.io.projectsave.FeatureListSaveTask.writeDataType(FeatureListSaveTask.java:301)
	at io.github.mzmine.modules.io.projectsave.FeatureListSaveTask.writeFeature(FeatureListSaveTask.java:321)
	at io.github.mzmine.modules.io.projectsave.FeatureListSaveTask.writeRow(FeatureListSaveTask.java:286)
	at io.github.mzmine.modules.io.projectsave.FeatureListSaveTask.saveFeatureData(FeatureListSaveTask.java:238)
	at io.github.mzmine.modules.io.projectsave.FeatureListSaveTask.run(FeatureListSaveTask.java:116)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)
```
@robinschmid @SteffenHeu Could you take a look at it?

**Comment by tomas-pluskal** [comment]
@BeniddirLab It seems the bug was in the "Same RT and m/z range gap filler" module. You can use the "Peak finder" module for gap filling instead, until we release a fix.

**Comment by robinschmid** [comment]
Is there a reason why you chose the other gap filling module?
Peak finder is the only multi threaded gap filling

**Comment by BeniddirLab** [comment]
@robinschmid it is just an old habit

**Comment by robinschmid** [comment]
Makes sense. 
For larger projects still good to try peak finder. 
Thanks for reporting the issue.
