### ISSUE TITLE
Mirror plot after NIST search

### ISSUE THREAD

**Issue by corinnabrungs** [mzmine/mzmine3#1448]
### Basic information

* My operating system and version:
* My MZmine version: 3.7.2

### What happened
After NIST Search, no mirror plot is possible in MZmine for the spectral match. 

2023-08-01 15:25:13 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask writeSpectraFile Writing spectra to file D:\mzminetemp\MZM2NIST3906358984076608597.MSP
2023-08-01 15:25:13 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask runNistMsSearch Executing C:\NIST23_MSMS\MSSEARCH\nistms$.exe /par=2 /instrument
2023-08-01 15:25:14 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask writeSpectraFile Writing spectra to file D:\mzminetemp\MZM2NIST10829671550774302069.MSP
2023-08-01 15:25:14 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask runNistMsSearch Executing C:\NIST23_MSMS\MSSEARCH\nistms$.exe /par=2 /instrument
2023-08-01 15:25:15 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask writeSpectraFile Writing spectra to file D:\mzminetemp\MZM2NIST8525362672284204870.MSP
2023-08-01 15:25:15 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask runNistMsSearch Executing C:\NIST23_MSMS\MSSEARCH\nistms$.exe /par=2 /instrument
2023-08-01 15:25:16 INFO   io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask run NIST MS Search completed
2023-08-01 15:25:16 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Running NIST MS Search for 20220613_100AGC_60000Res_pluskal_mce_1D1_C3_id.mzML msn trees done, status FINISHED
2023-08-01 15:25:16 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask writeSpectraFile Writing spectra to file D:\mzminetemp\MZM2NIST11376755076669958851.MSP
2023-08-01 15:25:16 FINEST io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask runNistMsSearch Executing C:\NIST23_MSMS\MSSEARCH\nistms$.exe /par=2 /instrument
2023-08-01 15:25:17 INFO   io.github.mzmine.modules.dataprocessing.id_nist.NistMsSearchTask run NIST MS Search completed
2023-08-01 15:25:17 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Running NIST MS Search for 20220613_100AGC_60000Res_pluskal_mce_1D1_C12_id.mzML msn trees done, status FINISHED
2023-08-01 15:25:48 INFO   io.github.mzmine.modules.visualization.featurelisttable_modular.FeatureTableFXMLTabAnchorPaneController selectedRowChanged selected: Spectral match
2023-08-01 15:25:48 FINE   io.github.mzmine.modules.visualization.featurelisttable_modular.FeatureTableFX handleClickOnCell Handle click on table cell
2023-08-01 15:25:53 SEVERE io.github.mzmine.datamodel.features.types.DataType lambda$createStandardColumn$1 Cannot set value from table cell to data type: Spectral match
2023-08-01 15:25:53 SEVERE io.github.mzmine.datamodel.features.types.DataType lambda$createStandardColumn$1 Cannot invoke "io.github.mzmine.datamodel.Scan.getScanNumber()" because the return value of "io.github.mzmine.util.spectraldb.entry.SpectralDBAnnotation.getQueryScan()" is null
java.lang.NullPointerException: Cannot invoke "io.github.mzmine.datamodel.Scan.getScanNumber()" because the return value of "io.github.mzmine.util.spectraldb.entry.SpectralDBAnnotation.getQueryScan()" is null
	at io.github.mzmine.util.spectraldb.entry.SpectralDBAnnotation.equals(SpectralDBAnnotation.java:269)
	at java.base/java.util.ArrayList.remove(ArrayList.java:624)
	at io.github.mzmine.datamodel.features.types.DataType.lambda$createStandardColumn$1(DataType.java:120)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.TreeTableCell.commitEdit(TreeTableCell.java:356)
	at io.github.mzmine.datamodel.features.types.fx.EditComboCellFactory$1.commitEdit(EditComboCellFactory.java:94)
	at javafx.scene.control.cell.CellUtils.lambda$listenToComboBoxSkin$5(CellUtils.java:368)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by SteffenHeu** [comment]
fixed #2921
