### ISSUE TITLE
`-batch` failing when DISPLAY is not defined (headless HPC cluster)

### ISSUE THREAD

**Issue by truatpasteurdotfr** [mzmine/mzmine3#1658]
### Basic information

* My operating system and version: RHEL8
* My MZmine version: MZmine_Linux_portable_3.9.0

### What happened
```
MZmine_Linux_portable_3.9.0/bin/MZmine   -batch workflow_complete_batch_short.xml 
```
fails to complete when DISPLAY is undefined (slurm batch mode, or interactive ssh without X forwarding)

relevant part of xml:
```
    <batchstep method="io.github.mzmine.modules.io.export_features_all_speclib_matches.ExportAllIdsGraphicalModule" parameter_version="1">
        <parameter name="Feature lists" type="NAME_PATTERN">
            <name_pattern>*FINALS_MERGED*</name_pattern>
        </parameter>
        <parameter name="Export directory">/pasteur/appa/scratch/test_ameng/out/graphics</parameter>
        <parameter name="Number of matches to export">2</parameter>
        <parameter name="DPI scaling factor">4</parameter>
        <parameter name="Export spectral library matches">false</parameter>
        <parameter name="Export lipid matches">false</parameter>
        <parameter name="Export shapes">true</parameter>
        <parameter name="Export mobilograms">false</parameter>
        <parameter name="Export feature images">false</parameter>
        <parameter name="Export pdf">false</parameter>
        <parameter name="Export png (⚠ freezes GUI)">true</parameter>
        <parameter name="Chart export parameters">
            <parameter name="Path">
                <current_file>/pasteur/appa/scratch/test_ameng/out/graphics</current_file>
                <last_file>/pasteur/appa/scratch/test_ameng/out/graphics</last_file>
            </parameter>
....
```
error listed:
```
...
2024-02-20 15:22:45 FINEST io.github.mzmine.taskcontrol.impl.TaskQueue addWrappedTask Adding task "Exporting all identifications." to the task controller queue
2024-02-20 15:22:45 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Starting processing of task Exporting all identifications.
2024-02-20 15:22:45 WARNING com.sun.javafx.application.PlatformImpl startup Unsupported JavaFX configuration: classes were loaded from 'unnamed module @24429cc8'
2024-02-20 15:22:45 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.UnsupportedOperationException: Unable to open DISPLAY while processing task Exporting all identifications.
java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
        at javafx.application.Platform.startup(Platform.java:111)
        at io.github.mzmine.main.MZmineCore.initJavaFxInHeadlessMode(MZmineCore.java:622)
        at io.github.mzmine.modules.io.export_features_all_speclib_matches.ExportAllIdsGraphicalTask.run(ExportAllIdsGraphicalTask.java:145)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)

java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
        at javafx.application.Platform.startup(Platform.java:111)
        at io.github.mzmine.main.MZmineCore.initJavaFxInHeadlessMode(MZmineCore.java:622)
        at io.github.mzmine.modules.io.export_features_all_speclib_matches.ExportAllIdsGraphicalTask.run(ExportAllIdsGraphicalTask.java:145)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)
2024-02-20 15:22:45 SEVERE io.github.mzmine.gui.HeadLessDesktop displayErrorMessage Unhandled exception in task Exporting all identifications.: java.lang.UnsupportedOperationException: Unable to open DISPLAY (GtkApplication.java:173)
```

**Comment by truatpasteurdotfr** [comment]
- If I run the same commands with DISPLAY defined on the same machine on an interactive `ssh -X` session the calculation is completed without error.
- if I change the `<parameter name="Number of matches to export">2</parameter>` to `0`, the run completes with/without `DISPLAY` being set.

**Comment by SteffenHeu** [comment]
Hi,

will be fixed in the next release.
