### ISSUE TITLE
Exception when loading RawDataOverviewWindow

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine3#1794]
Some user reported this exception when trying to open the raw data overview (mzmine 4.0.3 on windows):
````
Yes, I have this error: 

Could not load RawDataOverview.fxml
javafx.fxml.LoadException: 
file:/C:/Program%20Files/mzmine/app/mzmine-community-4.0.3.jar!/io/github/mzmine/modules/visualization/rawdataoverview/RawDataOverviewWindow.fxml:40

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2722)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2700)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2563)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2531)
	at io.github.mzmine.modules.visualization.rawdataoverview.RawDataOverviewPane.<init>(RawDataOverviewPane.java:53)
	at 
````

**Comment by Sanchezillana** [comment]
I have this issue. 

Windows 11 Enterprise 10.0.22631. 
Mzmine 4.0.3.
