### ISSUE TITLE
a problem of the function of 'help' in MZmine3

### ISSUE THREAD

**Issue by kkcau9118** [mzmine/mzmine3#32]
### Basic information

* My operating system: Windows10
* My MZmine version: MZmine3

### What happened
Hi,
When I tried to read the description of each parameter by clicking the button of 'help', it always shows 'loading help' without any text (please see the screenshot and the attached code below).
![image](https://user-images.githubusercontent.com/57988218/71259513-ed06ad80-2338-11ea-9cea-ab501a8e7ddb.png)
'Caused by: java.lang.ClassNotFoundException: io.github.mzmine.gui.impl.helpwindow.HelpWindowController
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:928)
	... 16 more'

**Comment by tomas-pluskal** [comment]
This is now fixed. Thanks for the report! There are a few more issues like this since the recent change from Swing to JavaFX for the main GUI. I am working on cleaning up the code and fixing these issues one by one.
