### ISSUE TITLE
ThermoRawFileImport on MS3 fails

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#447]
The raw data file import generates an mzML with only the last m/z isolation step. Usually mzML has multiple precursor ions sorted by MS level. See the snap below for MS3 from .raw.
@tomas-pluskal do you want to reach out about that?

![image](https://user-images.githubusercontent.com/10366914/144891684-5f601825-7e59-490f-8479-aede33207502.png)

**Comment by tomas-pluskal** [comment]
Could you upload a sample file? I'll write to them.

**Comment by robinschmid** [comment]
Orbitrap IDX up do MS4
[202112_DIMS_MS4_DDA_Orbitrap_IDX.zip](https://github.com/mzmine/mzmine3/files/7672950/202112_DIMS_MS4_DDA_Orbitrap_IDX.zip)

**Comment by tomas-pluskal** [comment]
Have you tried running the ThermoRawFileParser on this file?
I am getting this exception:
```
C:\ThermoRawFileParser>ThermoRawFileParser.exe -i 202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:29 INFO Started parsing 202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:30 INFO Processing 1280 MS scans
10% 2021-12-08 09:47:31 ERROR An unexpected error occured while parsing file:202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:31 ERROR System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at ThermoRawFileParser.Writer.MzMlSpectrumWriter.Write(IRawDataPlus rawFile, Int32 firstScanNumber, Int32 lastScanNumber) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/Writer/MzMlSpectrumWriter.cs:line 577
   at ThermoRawFileParser.RawFileParser.ProcessFile(ParseInput parseInput) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/RawFileParser.cs:line 139
   at ThermoRawFileParser.RawFileParser.TryProcessFile(ParseInput parseInput) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/RawFileParser.cs:line 62
```
It seems the parsing crashed after ~10% of the file. Not sure if that is also causing your problem with precursors, or if that is a different problem. Will investigate.

**Comment by tomas-pluskal** [comment]
https://github.com/compomics/ThermoRawFileParser/issues/126

**Comment by robinschmid** [comment]
Was fixed in the parser so we should update the parser internally

**Comment by titodamiani** [comment]
@robinschmid @tomas-pluskal has this been fixed? Or it's still an open issue?

**Comment by tomas-pluskal** [comment]
I think we still have not updated the parser..

**Comment by SteffenHeu** [comment]
@robinschmid can you comment if this is still an issue?

**Comment by ansgarkorf** [comment]
Should be fine after Tomas PR: #771
