### ISSUE TITLE
[Bug] Ion Identity related fields are not kept when reloading a project

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#577]
### Basic information

* My operating system: MacOS 12.3
* My MZmine version: 3.0.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

I tried opening a previously created project and everything related to Ion Identity is gone.
I expect this to be saved within the project. I tried both `standalone` and `referencing` export of the project, leading to the same issue.

Furthermore, if I try performing the IIN steps on the loaded project, I got some errors:
```
2022-03-08 10:09:45 SEVERE io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask run Adduct search error
java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getMaxDataPointIntensity()" is null
	at io.github.mzmine.datamodel.identities.iontype.IonNetwork.calcNeutralMass(IonNetwork.java:303)
	at io.github.mzmine.datamodel.identities.iontype.IonNetwork.getAvgRT(IonNetwork.java:313)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.getValue(IonNetworkSorter.java:61)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.compare(IonNetworkSorter.java:44)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.compare(IonNetworkSorter.java:32)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.mzmine.datamodel.identities.iontype.IonNetworkLogic.renumberNetworks(IonNetworkLogic.java:614)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.refineAndFinishNetworks(IonNetworkingTask.java:189)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.annotateGroups(IonNetworkingTask.java:156)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.run(IonNetworkingTask.java:122)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
```
```
2022-03-08 10:09:45 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception io.github.msdk.MSDKRuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getMaxDataPointIntensity()" is null while processing task Identification of adducts, in-source fragments and clusters in Aligned feature list 13C gaps dup corr PEARSON r greq 0.65 dp greq 5 corr PEARSON r greq 0.85 dp greq 5 
io.github.msdk.MSDKRuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getMaxDataPointIntensity()" is null
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.run(IonNetworkingTask.java:130)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "io.github.mzmine.datamodel.features.FeatureListRow.getMaxDataPointIntensity()" is null
	at io.github.mzmine.datamodel.identities.iontype.IonNetwork.calcNeutralMass(IonNetwork.java:303)
	at io.github.mzmine.datamodel.identities.iontype.IonNetwork.getAvgRT(IonNetwork.java:313)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.getValue(IonNetworkSorter.java:61)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.compare(IonNetworkSorter.java:44)
	at io.github.mzmine.datamodel.identities.iontype.networks.IonNetworkSorter.compare(IonNetworkSorter.java:32)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.mzmine.datamodel.identities.iontype.IonNetworkLogic.renumberNetworks(IonNetworkLogic.java:614)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.refineAndFinishNetworks(IonNetworkingTask.java:189)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.annotateGroups(IonNetworkingTask.java:156)
	at io.github.mzmine.modules.dataprocessing.id_ion_identity_networking.ionidnetworking.IonNetworkingTask.run(IonNetworkingTask.java:122)
	... 1 more
```

* Please include all parameter values for the MZmine modules you used. 

Later if needed

* Please upload screenshots of any errors and your log/mzmine.log file.

See above

* Please upload an MZmine project file that demonstrates the problem you are reporting.

Later if needed

**Comment by SteffenHeu** [comment]
The IIN data model is not yet implemented for load/save. @robinschmid Will work on this. 

However, the other issue should be unrelated to the IIN stuff. Can you share the standalone project please? I was not able to reproduce the issue.

**Comment by Adafede** [comment]
Here:

[Archive.zip](https://github.com/mzmine/mzmine3/files/8206776/Archive.zip)

(both batch.xml and standalone project)

Normally, just open the project, and try to `Feature grouping > Ion identity networking` again and the severe warning should appear.

**Comment by robinschmid** [comment]
Already on the list but thanks for reporting. We still need to save both the grouping and the Ion identities.

**Comment by robinschmid** [comment]
For now you can import the project and run metaCorrelate and Ion identity networking
