### ISSUE TITLE
No SRM scans found in mzML

### ISSUE THREAD

**Issue by zongqzhang** [mzmine/mzmine3#628]
### Basic information

* My operating system: windows x64
* My MZmine version: mzmine 3

### What happened

When I first opened this software in the morning, I could perform peak operation；When I opened it for the second time, the following prompt appeared. What's the problem？

java.lang.Exception: No scans found
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_all.MsDataImportAndMassDetectWrapperTask.run(MsDataImportAndMassDetectWrapperTask.java:96)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
2022-03-28 14:22:42 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Applying mass detection on P210902806.raw done, status FINISHED
2022-03-28 14:22:42 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.msdk.MzMLFileImportMethod execute Parsing Complete
java.lang.Exception: No scans found
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_all.MsDataImportAndMassDetectWrapperTask.run(MsDataImportAndMassDetectWrapperTask.java:96)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
2022-03-28 14:22:42 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Applying mass detection on P210902805.raw done, status FINISHED
2022-03-28 14:22:42 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.msdk.MzMLFileImportMethod execute Parsing Complete
java.lang.Exception: No scans found
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_all.MsDataImportAndMassDetectWrapperTask.run(MsDataImportAndMassDetectWrapperTask.java:96)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
2022-03-28 14:22:42 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Applying mass detection on P210902807.raw done, status FINISHED
2022-03-28 14:22:42 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.msdk.MzMLFileImportMethod execute Parsing Complete
java.lang.Exception: No scans found
        at io.github.mzmine.modules.io.import_rawdata_thermo_raw.ThermoRawImportTask.run(ThermoRawImportTask.java:185)
        at io.github.mzmine.modules.io.import_rawdata_all.MsDataImportAndMassDetectWrapperTask.run(MsDataImportAndMassDetectWrapperTask.java:96)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
2022-03-28 14:22:42 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Applying mass detection on P210902804.raw done, status FINISHED

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by zongqzhang** [comment]
My MZmine version: mzmine 3.0.11-beta

**Comment by zongqzhang** [comment]
<img width="769" alt="9589beababe4ca4ccdf776b1b750ee5" src="https://user-images.githubusercontent.com/102505228/160339944-b5deb4b1-cddb-4da5-be75-20449d0e705b.png">
<img width="978" alt="8908d206436d08ffc9be7dfefe7029a" src="https://user-images.githubusercontent.com/102505228/160339943-910cca2b-0545-4b53-b7d5-78777de4a686.png">

**Comment by SteffenHeu** [comment]
Hi zongqzhang,

there seems to be a problem with the data file. Do other files work or is it only this particular one?

**Comment by zongqzhang** [comment]
> Hi zongqzhang,
> 
> there seems to be a problem with the data file. Do other files work or is it only this particular one?

Hi SteffenHeu,

All files are imported like this, and I downloaded mzmine3 again, but I still can't import files

**Comment by SteffenHeu** [comment]
Mhhh...
We use the thermo raw file parser internally for the import. If you try to convert the files to mzml via the raw file parser, does it work?

**Comment by tomas-pluskal** [comment]
zongqzhang, can you upload one of the files somewhere?

**Comment by zongqzhang** [comment]
> zongqzhang, can you upload one of the files somewhere?
Here: [files.zip](https://github.com/mzmine/mzmine3/files/8360557/files.zip)

**Comment by zongqzhang** [comment]
> Mhhh... We use the thermo raw file parser internally for the import. If you try to convert the files to mzml via the raw file parser, does it work?

Mzml format files can't be opened either. Maybe I'll try another computer

**Comment by SteffenHeu** [comment]
Hi, 

i figured out the problem. We do not support SRM data because of the way they are stored in the mzML. Sorry.
