### ISSUE TITLE
Targeted Feature Extraction with GC Data fails at join alignment in batch mode

### ISSUE THREAD

**Issue by LoopyFig** [mzmine/mzmine3#712]
### Basic information

* My operating system: Ubuntu 20.04.4
* My MZmine version: MZmine 3.0.21-beta
* openjdk version: 17.0.2

### What happened

* I am attempting to run a targeted feature extraction of GC MS data in batch mode. My input are pre-centroided mzXML files (because you can't use raw input on a linux machine).
* At first I tried to run the data through the targeted feature extraction step directly, but I found that this produced nonsense results. Thus, I added a mass detection step with the centroid option.
* This seemed to partially fix things, but now the process breaks when I try to put the feature list through join alignment. I have tried the default join aligner and the ADAP aligner recommended for GC data. I have gotten different errors in either case.

* for the standard join alignment, these were the relevant parts of the batch file:
```
    <batchstep method="io.github.mzmine.modules.dataprocessing.featdet_massdetection.MassDetectionModule">
        <parameter name="Raw data files" type="BATCH_LAST_FILES"/>
        <parameter name="Scans">
            <polarity>POSITIVE</polarity>
            <spectrum_type>CENTROIDED</spectrum_type>
            <ms_level>1</ms_level>
            <scan_definition/>
        </parameter>
        <parameter name="Scan types (IMS)">All scan types</parameter>
        <parameter name="Mass detector" selected_item="Centroid">
            <module name="Centroid">
                <parameter name="Noise level">1000.0</parameter>
                <parameter name="Detect isotope signals below noise level" selected="true">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>0.001</absolutetolerance>
                        <ppmtolerance>5.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
            <module name="Exact mass">
                <parameter name="Noise level"/>
                <parameter name="Detect isotope signals below noise level" selected="false">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>5.0E-4</absolutetolerance>
                        <ppmtolerance>10.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
            <module name="Local maxima">
                <parameter name="Noise level"/>
            </module>
            <module name="Recursive threshold">
                <parameter name="Noise level"/>
                <parameter name="Min m/z peak width"/>
                <parameter name="Max m/z peak width"/>
            </module>
            <module name="Wavelet transform">
                <parameter name="Noise level"/>
                <parameter name="Scale level"/>
                <parameter name="Wavelet window size (%)"/>
            </module>
            <module name="Auto">
                <parameter name="Noise level">1000.0</parameter>
                <parameter name="Detect isotope signals below noise level" selected="false">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>5.0E-4</absolutetolerance>
                        <ppmtolerance>10.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
        </parameter>
        <parameter name="Output netCDF filename (optional)" selected="false"/>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.featdet_targeted.TargetedFeatureDetectionModule">
        <parameter name="Raw data files" type="BATCH_LAST_FILES"/>
        <parameter name="MS level">1</parameter>
        <parameter name="Name suffix">detectedPeak</parameter>
        <parameter name="Feature list file">
            <current_file>/data/Target_list_final_03242022.csv</current_file>
            <last_file>/data/Target_list_final_03242022.csv</last_file>
        </parameter>
        <parameter name="Field separator">,</parameter>
        <parameter name="Ignore first line">true</parameter>
        <parameter name="Intensity tolerance">0.5</parameter>
        <parameter name="Noise level">1000.0</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.001</absolutetolerance>
            <ppmtolerance>5.0</ppmtolerance>
        </parameter>
        <parameter name="Retention time tolerance" unit="MINUTES">0.5</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Feature list name">Aligned feature list</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.001</absolutetolerance>
            <ppmtolerance>5.0</ppmtolerance>
        </parameter>
        <parameter name="Weight for m/z">1.0</parameter>
        <parameter name="Retention time tolerance" unit="MINUTES">0.2</parameter>
        <parameter name="Weight for RT">1.0</parameter>
        <parameter name="Mobility tolerance" selected="false"/>
        <parameter name="Mobility weight">1.0</parameter>
        <parameter name="Require same charge state">false</parameter>
        <parameter name="Require same ID">true</parameter>
        <parameter name="Compare isotope pattern" selected="false">
            <parameter name="Isotope m/z tolerance"/>
            <parameter name="Minimum absolute intensity"/>
            <parameter name="Minimum score"/>
        </parameter>
        <parameter name="Compare spectra similarity" selected="false">
            <parameter name="Spectral m/z tolerance">
                <absolutetolerance>0.001</absolutetolerance>
                <ppmtolerance>10.0</ppmtolerance>
            </parameter>
            <parameter name="MS level">1</parameter>
            <parameter name="Compare spectra similarity" selected_item="Weighted dot-product cosine">
                <module name="Weighted dot-product cosine">
                    <parameter name="Weights">MassBank (mz^2 * I^0.5)</parameter>
                    <parameter name="Minimum  cos similarity">0.7</parameter>
                    <parameter name="Handle unmatched signals">KEEP ALL AND MATCH TO ZERO</parameter>
                </module>
                <module name="Composite dot -product identity (similar to NIST search)">
                    <parameter name="Weights">MassBank (mz^2 * I^0.5)</parameter>
                    <parameter name="Minimum  cos similarity">0.7</parameter>
                    <parameter name="Handle unmatched signals">KEEP ALL AND MATCH TO ZERO</parameter>
                </module>
            </parameter>
        </parameter>
        <parameter name="Original feature list">KEEP</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.filter_peakcomparisonrowfilter.PeakComparisonRowFilterModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Name suffix">filtered</parameter>
        <parameter name="1st peak column to compare (zero indexed)">0</parameter>
        <parameter name="2nd peak column to compare (zero indexed)">1</parameter>
        <parameter name="Fold change range : log2(peak1/peak2)" selected="false">
            <min>-5.0</min>
            <max>5.0</max>
        </parameter>
        <parameter name="m/z difference range : peak1 to peak2 (ppm)" selected="true">
            <min>-5.0</min>
            <max>5.0</max>
        </parameter>
        <parameter name="RT difference range : peak1 to peak2 (min)" selected="true">
            <min>-0.1</min>
            <max>0.1</max>
        </parameter>
        <parameter name="Remove source feature list after filtering">true</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.io.export_features_csv_legacy.LegacyCSVExportModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Filename">
            <current_file>feature_align_filter.csv</current_file>
            <last_file>feature_align_filter.csv</last_file>
        </parameter>
        <parameter name="Field separator">,</parameter>
        <parameter name="Export common elements">
            <item>Export row m/z</item>
            <item>Export row retention time</item>
            <item>Export row identity (main ID)</item>
        </parameter>
        <parameter name="Export data file elements">
            <item>Peak area</item>
        </parameter>
        <parameter name="Export quantitation results and other information">false</parameter>
        <parameter name="Identification separator">;</parameter>
        <parameter name="Filter rows">ALL</parameter>
    </batchstep>
```

* the error looked like this:
```
2022-06-02 08:50:18 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.IllegalArgumentException: Comparison method violates its general contract! while processing task Join aligner, Aligned feature list (198 feature lists)
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
        at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
        at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
        at java.base/java.util.TimSort.sort(TimSort.java:245)
        at java.base/java.util.Arrays.sort(Arrays.java:1307)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerTask.alignRowsOnBaseRows(JoinAlignerTask.java:332)
        at io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerTask.run(JoinAlignerTask.java:237)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)

java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
        at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
        at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
        at java.base/java.util.TimSort.sort(TimSort.java:245)
        at java.base/java.util.Arrays.sort(Arrays.java:1307)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerTask.alignRowsOnBaseRows(JoinAlignerTask.java:332)
        at io.github.mzmine.modules.dataprocessing.align_join.JoinAlignerTask.run(JoinAlignerTask.java:237)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
2022-06-02 08:50:18 SEVERE io.github.mzmine.gui.HeadLessDesktop displayErrorMessage Unhandled exception in task Join aligner, Aligned feature list (198 feature lists): java.lang.IllegalArgumentException: Comparison method violates its general contract! (TimSort.java:903)

```
* but when i tried to use the adap aligner with this batch file:
```
    <batchstep method="io.github.mzmine.modules.dataprocessing.featdet_massdetection.MassDetectionModule">
        <parameter name="Raw data files" type="BATCH_LAST_FILES"/>
        <parameter name="Scans">
            <polarity>POSITIVE</polarity>
            <spectrum_type>CENTROIDED</spectrum_type>
            <ms_level>1</ms_level>
            <scan_definition/>
        </parameter>
        <parameter name="Scan types (IMS)">All scan types</parameter>
        <parameter name="Mass detector" selected_item="Centroid">
            <module name="Centroid">
                <parameter name="Noise level">1000.0</parameter>
                <parameter name="Detect isotope signals below noise level" selected="true">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>0.001</absolutetolerance>
                        <ppmtolerance>5.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
            <module name="Exact mass">
                <parameter name="Noise level"/>
                <parameter name="Detect isotope signals below noise level" selected="false">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>5.0E-4</absolutetolerance>
                        <ppmtolerance>10.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
            <module name="Local maxima">
                <parameter name="Noise level"/>
            </module>
            <module name="Recursive threshold">
                <parameter name="Noise level"/>
                <parameter name="Min m/z peak width"/>
                <parameter name="Max m/z peak width"/>
            </module>
            <module name="Wavelet transform">
                <parameter name="Noise level"/>
                <parameter name="Scale level"/>
                <parameter name="Wavelet window size (%)"/>
            </module>
            <module name="Auto">
                <parameter name="Noise level">1000.0</parameter>
                <parameter name="Detect isotope signals below noise level" selected="false">
                    <parameter name="Chemical elements">H,C,N,O,S</parameter>
                    <parameter name="m/z tolerance">
                        <absolutetolerance>5.0E-4</absolutetolerance>
                        <ppmtolerance>10.0</ppmtolerance>
                    </parameter>
                    <parameter name="Maximum charge of isotope m/z">1</parameter>
                </parameter>
            </module>
        </parameter>
        <parameter name="Output netCDF filename (optional)" selected="false"/>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.featdet_targeted.TargetedFeatureDetectionModule">
        <parameter name="Raw data files" type="BATCH_LAST_FILES"/>
        <parameter name="MS level">1</parameter>
        <parameter name="Name suffix">detectedPeak</parameter>
        <parameter name="Feature list file">
            <current_file>/data/Target_list_final_03242022.csv</current_file>
            <last_file>/data/Target_list_final_03242022.csv</last_file>
        </parameter>
        <parameter name="Field separator">,</parameter>
        <parameter name="Ignore first line">true</parameter>
        <parameter name="Intensity tolerance">0.5</parameter>
        <parameter name="Noise level">1000.0</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.001</absolutetolerance>
            <ppmtolerance>5.0</ppmtolerance>
        </parameter>
        <parameter name="Retention time tolerance" unit="MINUTES">0.5</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.align_adap3.ADAP3AlignerModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Min confidence (between 0 and 1)">0.7</parameter>
        <parameter name="Retention time tolerance" unit="MINUTES">0.2</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.001</absolutetolerance>
            <ppmtolerance>5.0</ppmtolerance>
        </parameter>
        <parameter name="Score threshold (between 0 and 1)">0.75</parameter>
        <parameter name="Score weight (between 0 and 1)">0.1</parameter>
        <parameter name="Retention time similarity">Retention Time Difference (fast)</parameter>
        <parameter name="Aligned Feature List Name">Aligned feature list</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.dataprocessing.filter_peakcomparisonrowfilter.PeakComparisonRowFilterModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Name suffix">filtered</parameter>
        <parameter name="1st peak column to compare (zero indexed)">0</parameter>
        <parameter name="2nd peak column to compare (zero indexed)">1</parameter>
        <parameter name="Fold change range : log2(peak1/peak2)" selected="false">
            <min>-5.0</min>
            <max>5.0</max>
        </parameter>
        <parameter name="m/z difference range : peak1 to peak2 (ppm)" selected="true">
            <min>-5.0</min>
            <max>5.0</max>
        </parameter>
        <parameter name="RT difference range : peak1 to peak2 (min)" selected="true">
            <min>-0.1</min>
            <max>0.1</max>
        </parameter>
        <parameter name="Remove source feature list after filtering">true</parameter>
    </batchstep>
    <batchstep method="io.github.mzmine.modules.io.export_features_csv_legacy.LegacyCSVExportModule">
        <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS"/>
        <parameter name="Filename">
            <current_file>feature_align_filter.csv</current_file>
            <last_file>feature_align_filter.csv</last_file>
        </parameter>
        <parameter name="Field separator">,</parameter>
        <parameter name="Export common elements">
            <item>Export row m/z</item>
            <item>Export row retention time</item>
            <item>Export row identity (main ID)</item>
        </parameter>
        <parameter name="Export data file elements">
            <item>Peak area</item>
        </parameter>
        <parameter name="Export quantitation results and other information">false</parameter>
        <parameter name="Identification separator">;</parameter>
        <parameter name="Filter rows">ALL</parameter>
    </batchstep>
```

* which produced this error:
```
2022-06-02 15:53:12 INFO   io.github.mzmine.modules.dataprocessing.align_adap3.ADAP3AlignerTask run Started ADAP Peak Alignment
2022-06-02 15:53:12 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Error of task ADAP Aligner, Aligned feature list (198 feature lists): Incorrect Feature Lists:
ADAP Alignment requires mass spectra (or isotopic patterns) of peaks. No spectra found.
2022-06-02 15:53:12 SEVERE io.github.mzmine.gui.HeadLessDesktop displayErrorMessage Incorrect Feature Lists:
ADAP Alignment requires mass spectra (or isotopic patterns) of peaks. No spectra found.

```
* I could really use some help getting this to work! am I using one of these steps in a way that I'm not supposed to? is there something up with my java version? is there a guide on specifically targeted gc extraction? thanks!

**Comment by robinschmid** [comment]
This is some really weird behavior. 

Is it GC-EI MS?
Why are you not running through the general workflow with ADAP chromatogram builder and any resolver

**Comment by LoopyFig** [comment]
> This is some really weird behavior.
> 
> Is it GC-EI MS? Why are you not running through the general workflow with ADAP chromatogram builder and any resolver

The lab specifically requested a targeted feature extraction. They are hoping this will result in greater accuracy and less extraction time (there's a terabyte of data)

**Comment by robinschmid** [comment]
The targeted feature extraction is not used much and therefore not well maintained and updated. 
We made a lot of progress on memory management and speeds in the general processing workflow.

We usually do this for ~1000 data files:
- convert to mzML as centroid data files
- mass detection on all MS levels
- ADAP chromatogram builder
- Local minimum resolver (fast) or ADAP resolver (more complex) both produce good results
- Then you can either run the rest of the ADAP workflow for GC with spectral deconvolution + alignment

**Comment by LoopyFig** [comment]
I am trying the untargeted approach now as you suggested (though now I have new issues at spectral deconvolution that I'm reporting in a different question).

that said, the process failed with the targeted approach during join alignment due to some error with the java function "TimSort". If possible, I'd like to know if there's a recommended java version or something for mzmine.

**Comment by robinschmid** [comment]
mzmine comes with a java version so no need to install anything.

Lets close it here and open new issues if new things come up. Hope that the deconvolution now works since the latest development build version >=3.1.3. 
see #728
