### ISSUE TITLE
[bug] Export to GNPS-FBMN/IIMN

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#818]
### Basic information

* My operating system: MacOS
* My MZmine version: 3.1.0-beta

### What happened

According to https://mzmine.github.io/mzmine_documentation/module_docs/GNPS_export/gnps_export.html, the *comprehensive* export can be used for GNPS use. However, this does not seem to be the case. I just ran a job with the new vs legacy version, the old one works, the new one gives me the following error:

```
Number of Features 2312
ROW SUM NORM
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/clusterinfosummary_for_featurenetworks.py", line 262, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/clusterinfosummary_for_featurenetworks.py", line 258, in main
    process(args.params_xml, args.consensus_feature_file, metadata_files, args.mgf_filename, args.output_clusterinfo_summary)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/clusterinfosummary_for_featurenetworks.py", line 156, in process
    file_quants = [float(quantification_object[filename_header]) for quantification_object in quantification_list]
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/clusterinfosummary_for_featurenetworks.py", line 156, in <listcomp>
    file_quants = [float(quantification_object[filename_header]) for quantification_object in quantification_list]
ValueError: could not convert string to float: 'DETECTED'
Tool execution terminates abnormally with exit code [1]
```

also tagging @mwang87 in case, tell me if you want me to open a related issue on GNPS GitHub! 😉

**Comment by robinschmid** [comment]
Did you run the quick start or the latest GNPS version. We still need to update the version that is used by the quick start. 
Or maybe its not yet released but I thought @mwang87 released the version where the comprehensive data table works.

**Comment by Adafede** [comment]
latest, tagged as 28.2

**Comment by robinschmid** [comment]
Okay then its not released on GNPS
