### ISSUE TITLE
2D ion map / feature representation

### ISSUE THREAD

**Issue by samuelbertrand44** [mzmine/mzmine3#928]
### Basic information

* My operating system: Windows 11
* My MZmine version: 3.2.8

### What happened

Hi,

When I inspect the feature list using 2D maps (2D plot) it was possible to overlay the feature list (MZmine2). It loog like it is possible to do the same in MZmine3.2.8, however, the features marks never show up on the map.
![Image1](https://user-images.githubusercontent.com/59165223/193692401-c7d8e5ac-3d9c-4572-828e-37228e851aa8.png)

is this a known issue ?

thanks in advance for your answer.

Samuel

![Image1](https://user-images.githubusercontent.com/59165
[Image&log.zip](https://github.com/mzmine/mzmine3/files/9701278/Image.log.zip)
223/193692544-ad6bb7ef-301a-41ae-863c-74a8519659ea.png)

**Comment by samuelbertrand44** [comment]
I tried again today with the consol open.

_**2022-10-04 09:21:36 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 206 ms
Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:651)
        at io.github.mzmine.modules.visualization.twod.TwoDBottomPanel.lambda$new$1(TwoDBottomPanel.java:118)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8889)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
        at com.sun.glass.ui.View.notifyMouse(View.java:942)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-10-04 09:21:55 FINEST io.github.mzmine.modules.visualization.twod.TwoDPlot loadFeatureList Loading featurelist qc_1.mzML chr deisotoped**_

it look like the last step (feature rendering) is never finishing.

can you help ?

thanks a lot.

**Comment by robinschmid** [comment]
@omokshyna were you looking into this already or was it a different one?

**Comment by samuelbertrand44** [comment]
I do not really understand the question. I am sorry.

I use a lot the 2D feature maping on 2D-ion map but sice MZmine3 it does not seems to work properly.

thanks in advance for the help.

**Comment by omokshyna** [comment]
@robinschmid It was a different one. @samuelbertrand44, I'll check the issue and will get back to you.

**Comment by robinschmid** [comment]
thanks

**Comment by samuelbertrand44** [comment]
> I'll check the issue and will get back to you.

ok,  thans in advance.

anyway, if you need more inforamtion, do not hesitate to ask.

**Comment by fuchsi3010** [comment]
hi, i'm having the same issue... i have a lot of features in my feature list:
![image](https://user-images.githubusercontent.com/37498115/203807695-d5ce69c5-2948-4d3b-9308-60d445cb4eeb.png)
but if i go to visualize (ms data files tab → select file → show 2D plot → ok; in 2D Visializer: all features → _select feature list_ → load) i get 2 or 3 annotations:
![image](https://user-images.githubusercontent.com/37498115/203808488-488954cd-700b-4541-a463-d3a8d6721304.png)
no annotations appear if i zoom in further:
![image](https://user-images.githubusercontent.com/37498115/203808788-3971ed91-2d5b-4d61-a1be-ed2affd42365.png)

the logs dont tell me something useful:
``` 
2022-11-24 15:26:57 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection resetSelection Resetting file selection. Previously evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:26:57 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection getMatchingRawDataFiles Setting file selection. Evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection getMatchingRawDataFiles Setting file selection. Evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection resetSelection Resetting file selection. Previously evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection getMatchingRawDataFiles Setting file selection. Evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection resetSelection Resetting file selection. Previously evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.main.MZmineCore runMZmineModule Module 2D visualizer called at 2022-11-24T14:27:27.751221261Z
2022-11-24 15:27:27 FINEST io.github.mzmine.parameters.parametertypes.selectors.RawDataFilesSelection getMatchingRawDataFiles Setting file selection. Evaluated files: [4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML]
2022-11-24 15:27:27 FINEST io.github.mzmine.taskcontrol.impl.TaskQueue addWrappedTask Adding task "Updating 2D visualizer of 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML" to the task controller queue
2022-11-24 15:27:27 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Starting processing of task Updating 2D visualizer of 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML
2022-11-24 15:27:27 INFO   io.github.mzmine.taskcontrol.impl.WorkerThread run Processing of task Updating 2D visualizer of 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML done, status FINISHED
2022-11-24 15:27:27 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 213 ms
2022-11-24 15:27:45 FINEST io.github.mzmine.modules.visualization.twod.TwoDPlot loadFeatureList Loading featurelist 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML detectedPeak
2022-11-24 15:27:49 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 258 ms
2022-11-24 15:27:49 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 129 ms
2022-11-24 15:27:49 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 219 ms
2022-11-24 15:27:50 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 213 ms
2022-11-24 15:27:50 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 137 ms
2022-11-24 15:27:50 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 131 ms
2022-11-24 15:27:50 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 216 ms
2022-11-24 15:27:50 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 159 ms
2022-11-24 15:27:51 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 236 ms
2022-11-24 15:27:51 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 254 ms
2022-11-24 15:27:51 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 163 ms
2022-11-24 15:27:51 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 146 ms
2022-11-24 15:27:53 FINEST io.github.mzmine.modules.visualization.twod.TwoDPlot loadFeatureList Loading featurelist 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML detectedPeak
2022-11-24 15:27:55 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 239 ms
2022-11-24 15:27:55 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 332 ms
2022-11-24 15:27:56 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 159 ms
2022-11-24 15:27:56 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 218 ms
2022-11-24 15:27:57 FINEST io.github.mzmine.modules.visualization.twod.TwoDPlot loadFeatureList Loading featurelist 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML detectedPeak
2022-11-24 15:28:00 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 309 ms
2022-11-24 15:28:01 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 246 ms
2022-11-24 15:28:01 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 196 ms
2022-11-24 15:28:01 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 145 ms
2022-11-24 15:31:02 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 171 ms
2022-11-24 15:31:05 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 166 ms
2022-11-24 15:31:10 FINEST io.github.mzmine.modules.visualization.twod.TwoDPlot loadFeatureList Loading featurelist 4680_C1_9 tot.prot._19.09.2021_07-46-33_2021-09-17_JK_PLANCLAN_PASEF_V8_reversed_29_1.mzML detectedPeak
2022-11-24 15:31:10 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 168 ms
2022-11-24 15:31:10 FINEST io.github.mzmine.modules.visualization.twod.TwoDXYPlot render Finished rendering 2D visualizer, 145 ms
```

this is MzMine 3.2.8 portable on Manjaro Linux (Kernel 5.15) with openjdk 19.0.1 2022-10-18
thanks in advance for any help!

**Comment by samuelbertrand44** [comment]
This issue does not seems to be corrected in the 3.9 version. 

did you get time to correct it?

do you want to discuss it?
